### ISSUE TITLE
Help with commands

### ISSUE THREAD

**Issue by r4club** [tejashah88/mcaternos-bot#2]
I runned the bot but how to start the server?? 
/start in discord dont worked pls help me

**Comment by tejashah88** [comment]
Hi @Nikolai980,

You need to mention the bot and say `start server` (ex. `@McAternosBot start server`)

**Comment by sintyx-host** [comment]
Thank you so much

**Comment by tippfehlr** [comment]
@tejashah88 This can be closed as well
