### ISSUE TITLE
Error at npm run start-prod

### ISSUE THREAD

**Issue by r4club** [tejashah88/mcaternos-bot#3]
$ npm run start-prod

> mcaternos-bot@1.0.0 start-prod C:\Users\nikol\OneDrive\Imágenes\Escritorio\botki now live\aternos botaaa\mcaternos-bot-master
> pm2 start bot.js --wait-ready

[PM2] Applying action restartProcessId on app [bot](ids: [ 1 ])
[PM2][ERROR] Process 1 not found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mcaternos-bot@1.0.0 start-prod: `pm2 start bot.js --wait-ready`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mcaternos-bot@1.0.0 start-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nikol\AppData\Roaming\npm-cache\_logs\2021-07-16T09_14_10_994Z-debug.log

Can you help me how to fix this ??

**Comment by tejashah88** [comment]
Can you post the content of the debug logs at that location?

**Comment by tejashah88** [comment]
Closing this due to no follow-up...
